README.md
- Adds a project README
- ...
- ...
#9 
/area control-plane
/area documentation
=> Adds initial content of the project README

sec-scanners-config.yaml
- should turn on security scanning in whitesource and protecode 
- ...
- ...
- #33 
- [example in btp-manager](https://github.com/kyma-project/btp-manager/blob/main/sec-scanners-config.yaml)
- [example in keda-manager](https://github.com/kyma-project/keda-manager/blob/main/sec-scanners-config.yaml )
/area control-plane
/kind feature
=> adds configuration for protecode and whitesource scanning

internal/controller/gardener_cluster_controller.go, internal/controller/gardener_cluster_controller_test.go
Please review after #37 
-  Infrastructure Manager removes secrets when Gardener Cluster CR is deleted.
- ...
- ...
#10 
/area control-plane
/kind feature
=> Infrastructure Manager removes secrets when Gardener Cluster CR is deleted

cmd/main.go, config/default/manager_gardener_secret_patch.yaml, config/rbac/role.yaml, config/samples/clusterinventory_v1_gardenercluster.yaml, internal/controller/gardener_cluster_controller.go, internal/gardener/KubeConfigProvider.go, internal/gardener/client.go
- KubeconfigProvider implemented
- KubeconfigProvider initialized on application startup
=> Fetching dynamic kubeconfig

api/v1/gardenercluster_types.go, internal/controller/gardener_cluster_controller.go
Fix cache error.
- fix cache error
- code cleanup
=> Fix cache error

internal/controller/gardener_cluster_controller.go
Refactor kubeconfig status.
See also: https://github.com/kyma-project/infrastructure-manager/issues/10
=> refactor kubeconfig status

api/v1/gardenercluster_types.go, config/crd/bases/infrastructuremanager.kyma-project.io_gardenerclusters.yaml
Update GardenerCluster CRD printed columns to show information about CR `state`, `runtime-id` and `shoot-name`.
E.g.
```
$ kubectl get gardenerclusters.infrastructuremanager.kyma-project.io -A
NAMESPACE    NAME         STATE   RUNTIME-ID   SHOOT-NAME   AGE
kcp-system   runtime-id   Ready   runtime-id   shoot-name   2m40s
```
- `STATE` and `RUNTIME-ID` columns added
=> Update GardenerCluster CRD printed columns

api/v1/gardenercluster_types.go, internal/controller/gardener_cluster_controller.go
Fix invalid condition status for errors in `GardenerCluster`.
- fix invalid condition status for errors in GardenerCluster
- fix context for kubeconfig secret deletion
- refactor status change persisting
=> Fix invalid condition status for errors in GardenerCluster

hack/benchmark/README.md, hack/benchmark/benchmark.sh, hack/benchmark/secret.template.json
=> add module benchmark

hack/benchmark/benchmark.sh, hack/benchmark/secret.template.json, internal/controller/gardener_cluster_controller.go
- Fix delete secret
- Update `create_secrets` benchmark function
=> Fix delete secret

Makefile, internal/controller/gardener_cluster_controller.go
Add predicates to filter out CR status changes.
=> Add predicates to filter out CR status changes

LICENCE
It seems that OSPO bot needs licences in both `root` and `LICENCES` directories...
- adds a licence file ( copied from https://github.com/kyma-project/lifecycle-manager/blob/main/LICENCE that has this issue resolved)  in a `root` directory
- ...
- ...
Fixes https://github.com/kyma-project/infrastructure-manager/issues/87
=> adds a licence file to the root directory

config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_config_patch.yaml, config/default/manager_gardener_secret_patch.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml
`kubectl -n kcp-system get service infrastructure-manager -o yaml | yq .spec.selector
control-plane: controller-manager` is pulling 2 other unrelated components' pods. 
- renaming from `controller-manager` to `infrastructure-manager`
- ...
- ...
=> renames control-manager to intrastructure-manager

Makefile, config/manager/manager.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml
renaming of:
- leader-election-role
- leader-election-rolebinding
- manager-role
- manager-rolebinding
#93
=> renames infrastructure manager roles and rolebindings

internal/controller/gardener_cluster_controller.go, internal/controller/gardener_cluster_controller_test.go
`lifecycle-manager` currently relies on label `operator.kyma-project.io/managed-by=lifecycle-manager`. 
- This PR sets that label **temporarily** to required.
- ...
- ...
=> managed-by secret label is set to lifecycle-manager

internal/controller/gardener_cluster_controller.go
Fix bug caused by timezone miss-matching.
=> Fix timezone miss-matching

docs/README.md
- describes `minimal-rotation-time` parameter
- ...
- ...
#98
=> describes minimal-rotation-time parameter

.github/workflows/golangci-lint.yaml, .github/workflows/run-vuln-check.yaml, Dockerfile, go.mod
- configures golang/govulncheck-action in this repository
- bumps golang to 1.21.5
- linter uses 1.25.1 version of golang
=> configures golang/govulncheck-action

go.mod, go.sum, internal/controller/find_last_sync_time.go, internal/controller/find_last_sync_time_test.go, internal/controller/gardener_cluster_controller.go, internal/controller/next_requeue.go, internal/controller/next_requeue_test.go
Add unit tests for requeue functions.
- add requeue tests
- project structure refactor
- refactor secret rotation logic to use common methods
=> Add requeue tests

internal/controller/gardener_cluster_controller.go, internal/controller/gardener_cluster_controller_test.go
Secrets are now managed by infrastructure-manager, the corresponding label should reflect that
- changes `managed-by` label from `lifecycle-manager` to `infrastructure-manager`.
- ...
- ...
- internal backlog item no. 4826 
- https://github.com/kyma-project/lifecycle-manager/pull/1160
=> changes managed-by label from lifecycle-manager to infrastructure-manager

.github/workflows/golangci-lint.yaml, internal/controller/find_last_sync_time_test.go, internal/controller/gardener_cluster_controller_test.go, internal/controller/next_requeue_test.go, internal/controller/suite_test.go
- upgrades golangci-lint to v4
- ...
- ...
Related PR in Kyma repo https://github.com/kyma-project/kyma/pull/18579
=> upgrades golangci-lint to v4 in IM

hack/runtime-migrator/main.go
- RuntimeID instead of shootname used for Runtime CR name
- ...
- ...
#183
=> RuntimeID instead of shootname used for Runtime CR name

config/manager/converter_config.yaml, converter_config.json, internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go, internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go, internal/controller/runtime/suite_test.go, internal/gardener/shoot/converter.go, internal/gardener/shoot/converter_test.go, internal/gardener/shoot/extender/exposure_classname_extender.go, internal/gardener/shoot/extender/kubernetes_version_test.go, internal/gardener/shoot/extender/maintenance.go, internal/gardener/shoot/extender/maintenance_test.go, internal/gardener/shoot/extender/network_filter.go
- Adds maintenance extender which allows configuration of auto-updates via `kubernetesVersion` and `machineImageVersion` 
- switches to k8s util `ptr.To`
#230
=> Maintenance extender

hack/shoot-comparator/pkg/shoot/matcher.go, hack/shoot-comparator/pkg/shoot/matcher_test.go, internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go, internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go, internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go, internal/controller/runtime/fsm/testing/shoot.go, internal/controller/runtime/fsm/utilz_for_test.go
- Matchers perform more granular comparison to make results easier to read
- Annotations are not compared as both KIM and Provisioner create different annotations set
- Shoot spec stored on the persistent volume does not contain fields that are not relevant for comparison 
- Shoot spec not stored on upgrade to align with the Provisioner
#185
=> Fixes for making shoot comparison easier

cmd/main.go, config/default/kustomization.yaml, config/default/manager_converter_config_patch.yaml, config/manager/converter_config.yaml
- add Config Map with converter config as Volume Mount to KIM deployment
https://github.com/kyma-project/infrastructure-manager/issues/320
=> Align KIM to use Config Map with converter config

docs/adr/assets/runtime-examples/aws-freemium.yaml, docs/adr/assets/runtime-examples/aws-minimal.yaml, docs/adr/assets/runtime-examples/aws-trial.yaml, docs/adr/assets/runtime-examples/aws.yaml, docs/adr/assets/runtime-examples/azure-fremium.yaml, docs/adr/assets/runtime-examples/azure-lite.yaml, docs/adr/assets/runtime-examples/azure.yaml, docs/adr/assets/runtime-examples/gcp.yaml, docs/adr/assets/runtime-examples/sap-converged-cloud.yaml, internal/controller/runtime/fsm/runtime_fsm_create_shoot.go, internal/controller/runtime/fsm/runtime_fsm_delete_kubeconfig.go
- Exemplary Runtime CR yamls fixed
- Status condition contains detailed error message from Gardener (temporary solution, in the future we must provide error category in the CR's status)
#332
=> Runtime CR examples updated

config/prometheus/monitor.yaml
- Modification requested by security audit
- Removes `bearerTokenFile` and `tlsConfig` from prometheus service monitor
- This is used only for local development and not very often  
- Verification would be time consuming and I did not test this change (minimal impact)
=> Removes bearerTokenFile and tlsConfig from prometheus service monitor

.github/workflows/golangci-lint.yaml, .github/workflows/run-tests.yaml, .github/workflows/run-vuln-check.yaml, go.mod, hack/shoot-comparator/Dockerfile, hack/shoot-comparator/go.mod
1. Update of golang version to `1.23.0` in GH actions 
2. Updated build image for shoot-comparator app to `golang:1.23.0-alpine3.20`
Updated GH actions:
- golangci-lint (change version format to SHA tag, to ensure safety, use latest version of golangci-lint, and increase timeout to 10 m)
- run-tests
- vulncheck
=> Configuration of GH workflows to use go version 1.23.0

hack/runtime-migrator/main.go
- Migrator no longer sets `worker.machine.architecture`, `worker.systemcomponents`, `worker.cri`
#342
=> Fixes to migrator that will remove unimportant differences

internal/auditlogging/auditlogging.go, internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go, internal/controller/runtime/fsm/runtime_fsm_configure_auditlog_test.go, internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go, internal/controller/runtime/runtime_controller_test.go
- proceed to immediately requeue if was Kubernetes conflict error during Gardener Shoot object update
=> Handle the Kubernetes conflict error in KIM Audit Log

internal/gardener/shoot/extender/dns_test.go, internal/gardener/shoot/extender/oidc.go, internal/gardener/shoot/extender/oidc_test.go
Adjusts feature parity of OIDC extension enablement between Provisioner and KIM. As for @tobiscr request:
> The Provisioner is enabling it only for new runtimes. In KIM, it looks like we enable it always - also for updates.
> Would KIM be able to detect if the RUntime was already created, or does it not know whether a Runtime is new or already exists?
- extension applied only if `"operator.kyma-project.io/created-by-migrator": "true"` is not set
- ...
- ...
- https://github.com/kyma-project/infrastructure-manager/issues/381
=> oidc extension added only if controlled-by-provisioner value is disabled

internal/gardener/shoot/extender/provider.go
In order to not changing the existing zones assignment during reconciliation of the old runtimes we need to remove the zones sorting.
- remove sorting the workers zones
=> Remove worker zones sorting

hack/shoot-comparator/pkg/errors/errors.go, hack/shoot-comparator/pkg/runtime/raw_extension_matcher.go, hack/shoot-comparator/pkg/runtime/raw_extension_matcher_test.go, hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_11.yaml, hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_12.yaml, hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_azure_21.yaml, hack/shoot-comparator/pkg/runtime/testdata/infra_cfg_openstack_11.yaml, hack/shoot-comparator/pkg/shoot/extensionmatcher.go, hack/shoot-comparator/pkg/shoot/matcher.go, hack/shoot-comparator/pkg/shoot/provider_matcher.go, hack/shoot-comparator/pkg/utilz/utilz.go
- raw extension comparator added
See also: https://github.com/kyma-project/infrastructure-manager/issues/342
=> Add raw extension comparator

config/default/manager_gardener_secret_patch.yaml, docs/README.md
- removes docs and configs for already deleted `runtime-reconciler-enabled` flag
- ...
- ...
- [Related commit](https://github.com/kyma-project/infrastructure-manager/commit/f3390d3e79c3986ba7a5c1a5edaccd4536bd2a87)
- internal/management-plane-config/5793 
- internal/management-plane-charts/2136
=> removes docs and configs for removed runtime-reconciler-enabled flag

hack/runtime-migrator/README.md, hack/runtime-migrator/cmd/migration.go, hack/runtime-migrator/internal/migration/results.go
- Migrator output made shorter
- Fixed issue in report
- Documentation added
#400
=> Final fixes in the migrator

hack/runtime-migrator/cmd/main.go, hack/runtime-migrator/cmd/migration.go, hack/runtime-migrator/go.mod, hack/runtime-migrator/go.sum, hack/runtime-migrator/internal/config/config.go, hack/runtime-migrator/internal/runtime/migrator.go, hack/runtime-migrator/internal/runtime/verifier.go
…per raw)
- Added ability to specify runtimes list in flat file
#470
=> WIP: Adjust migrator to audit log related changes

hack/runtime-migrator/cmd/migration.go, hack/shoot-comparator/pkg/runtime/raw_extension_matcher.go
- Fixed raw extension matcher
- Minor fix in error handling
=> Fixed issue with audit log extension comparison

internal/controller/runtime/suite_test.go, pkg/gardener/shoot/converter.go, pkg/gardener/shoot/extender/auditlogs/auditlogs_configuration_test.go, pkg/gardener/shoot/extender/provider_test.go, pkg/gardener/shoot/extender/seed_in_shoot_region.go, pkg/gardener/shoot/extender/seed_selector.go, pkg/gardener/shoot/extender/seed_selector_test.go
**Implementation**
When EnforceSeedLocation flag is enabled in Runtime CR  
Setting Shoot `seedSelector.matchLabels` field to the value 
`seed.gardener.cloud/region : <Shoot region>`
https://github.com/kyma-project/infrastructure-manager/issues/241
https://github.com/kyma-project/kyma/issues/18182
**Additional info**
There are some cases for HA dedicated seeds - please make sure this solution will work in case of HA clusters
https://github.com/kyma-project/kyma/issues/18182#issuecomment-2133446254
=> Add new extender to enforce configuration of shoot seed within the same region as the shoot

.github/dependabot.yml
Dependabot creates separate PRs for each dependency bump which makes merging them burdersome as each has to be approved after rebase to main.
- should group `k8s.io` PRs into a single PR
- should group `gardener` PRs into a single PR
- change only affects `minor` and `patch` - `major` bumps will be created as separate PRs
#500
=> grouping of k8s.io and gardener dependabot PRs

internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig.go, internal/controller/runtime/fsm/runtime_fsm_create_kubeconfig_test.go, internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go, internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go, internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
- Add gardener cluster recovery for patch operations
See also: https://github.com/kyma-project/infrastructure-manager/issues/443
=> Add gardener cluster recovery for patch operations

Makefile
aims to fix the following issue
```
cd config/manager && /Users/username/infrastructure-manager/bin/kustomize edit set image controller=custom-infrastructure-manager:0.0.1
bash: line 1:  9565 Killed: 9               /Users/username/open-source/infrastructure-manager/bin/kustomize edit set image controller=custom-infrastructure-manager:0.0.1
make: *** [deploy] Error 137
```
- bumps kustomize from v4.5.5 to v5.5.0
- ...
- ...
=> bumps kustomize from v4.5.5 to v5.5.0

hack/runtime-migrator/internal/runtime/migrator.go, internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go, internal/controller/runtime/fsm/runtime_fsm_configure_oidc_test.go
Handling exception case for Patch operation when `Disabled` field is missing from OIDC extension data in the shoot like following: 
```
extensions:
- type: shoot-oidc-service
- type: shoot-dns-service
```
In the old implementation the missing `Disabled` field was causing unexpected crash.
In the new implementation the missing `Disabled` filed is interpreted as **"Enabled by default"**
=> Handing missing Disabled field in OIDC extension data to avoid crash

internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go, internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
- Kim should not delete existing service accounts
- ...
- ...
=> Kim should not delete existing service accounts

cmd/main.go, docs/README.md, internal/controller/kubeconfig/gardener_cluster_controller.go, internal/controller/kubeconfig/suite_test.go, internal/controller/runtime/runtime_controller.go, internal/controller/runtime/suite_test.go
This PR allows to specify the number of workers for both controllers as program arguments
```
- --runtime-ctrl-workers-cnt=150
- --gardener-cluster-ctrl-workers-cnt=33
``` 
If no parameter is provided the with default value for each worker count is 25
=> Configurable number of workers for both controllers with default value 25

hack/runtime-migrator/cmd/backup/backup.go, hack/runtime-migrator/cmd/backup/main.go, hack/runtime-migrator/cmd/restore/main.go, hack/runtime-migrator/cmd/restore/restore.go, hack/runtime-migrator/internal/backup/backup.go, hack/runtime-migrator/internal/backup/output.go, hack/runtime-migrator/internal/initialisation/client.go, hack/runtime-migrator/internal/initialisation/params.go, hack/runtime-migrator/internal/restore/backupreader.go, hack/runtime-migrator/internal/restore/restorer.go, hack/runtime-migrator/internal/restore/results.go, hack/runtime-migrator/internal/shoot/util.go
- Backup for Cluster Role Bindings and OIDC
- Restore for Cluster Role Bindings and OIDC
#557
=> Implement backup and restore for Cluster Role Bindings and OIDC

internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go, internal/controller/runtime/suite_test.go
Fix of the bug - adding case of checking for `LastOperationStateError` Gardener `shoot.Status.LastOperation.State` in the code executed while waiting for shoot reconciliation. 
LastOperationStateError means it is a retryable error hence you should requeue the reconciliation with a short requeue time.
In preexisting code the `LastOperationStateError` was ignored and reconciliation loop was stopped with message:
`sFnWaitForShootReconcile - unknown shoot operation state, stopping state machine`
After the fix - when the `LastOperationStateError` occurs - the next reconciliation will be scheduled.
**Related issue:**
Internal-GH/kyma/backlog/issues/6615
=> Add handling of LastOperationStateError shoot operation state while waiting for reconciliation to complete

pkg/gardener/shoot/extender/provider.go, pkg/gardener/shoot/extender/provider_test.go
Second part of implementation of extending workers network zones config during Shoot update, mainly unit tests adjustments
First PR: https://github.com/kyma-project/infrastructure-manager/pull/656
GH Issue: https://github.com/kyma-project/kyma/issues/18774
=> Adjust unit tests for functionality of extending workers network zones config

.github/workflows/all-checks-passed.yml
We have to switch from `tide` which was preventing unintended merges of a PR to something else as it is no longer working.
- adds a gihtub workflow for [allcheckspassed](https://github.com/wechuli/allcheckspassed/tree/main) that assures that all checks passed 
- ...
- ...
- #666 - was merged even with a test failure
- https://github.com/kyma-project/test-infra/blob/main/.github/workflows/all-checks-passed.yml - this is used in `test-infra` repo
- [research on required checks ](https://github.com/kyma-project/test-infra/issues/12139#issuecomment-2408255908)
=> add gh workflow that should assure that all checks are passed before the merge

internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go, internal/controller/runtime/fsm/runtime_fsm_configure_oidc_test.go
Creating OIDCConnectResources was enabled for new clusters created with KIM only. It was disabled for the clusters created by the Provisioner.
- Removed check for migrated label in the OIDC Config step
=> Removed check for migrated label in OIDC step

.github/workflows/release.yaml, config/crd/crd-doc-config.yaml
- Automatically generates CRD documentation and attaches it as an asset to a release on a tag push
- Example release with the generated CRD docs can be found on [my fork ](https://github.com/Disper/infrastructure-manager/releases/tag/1.28.8). Manual verification can be done e.g. on a fork after merging this workflow and pushing a new tag `env KIM_VERSION=1.28.9 bash -c 'git tag -a $KIM_VERSION -m "$KIM_VERSION" && git push {YOUR_REMOTE} $KIM_VERSION'`
- ...
#1005
=> automatically generate crd documentation and add to a release

.github/workflows/all-checks-passed.yml, go.mod
Temporaily fix for the problem with  `golangci-lint-action` latest [release 8.0](https://github.com/golangci/golangci-lint-action/releases/tag/v8.0.0) not compatible with Golang 1.25.x.
```
Error: can't load config: the Go language version (go1.24) used to build golangci-lint is lower than the targeted Go version (1.25.0)
Failed executing command with error: can't load config: the Go language version (go1.24) used to build golangci-lint is lower than the targeted Go version (1.25.0)
Error: golangci-lint exit with code 3
Ran golangci-lint in 100ms
```
With this change we can migrate to Golang 1.25.x and we can merge all PR using new version of Golang even though golangci-lint-action fails. 
We can restore previous workflow after  `golangci-lint-action` is released with Go 1.25
=> Exclude golangci-lint from allcheckspassed GH action

cmd/main.go, internal/controller/runtime/fsm/runtime_fsm_create_shoot.go, internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go, pkg/config/config.go, pkg/gardener/shoot/converter.go, pkg/gardener/shoot/converter_test.go, pkg/gardener/shoot/extender/token/tokenExpiration.go, pkg/gardener/shoot/extender/token/tokenExpiration_test.go
Refactor the logic of setting `maxTokenExpiration`, and create default token time boundaries.
Field `MaxTokenExpiration` is configurable with the converter config file, and the allowed token lifetime duration will be between >= 30 days and <= 90 days.
- if value < 30 days, we log an warning and set it to 30 days in the code.
- if value is > 90 days, we log a warning and set to 90 days in the code.
- if value is missing, we log a warning and set it to 30 days
Field `ExtendTokenExpiration` is always set to `false` and it is not configuralbe
=> Refactor token expiration handling, create an default boundaries
