kyma-project/kyma-infrastructure-manager

- .github/ISSUE_TEMPLATE/feature-request.md
Tests the **Updates to issue forms** feature from https://github.com/orgs/community/discussions/63381
- Adds default labels and project to feature-request.md
- ...
- ...
> Adds default labels and project to feature-request.md

- .github/ISSUE_TEMPLATE/feature-request.md
Should fix the change done in #43
> Issue template

- README.md
- docs/README.md
- please see the title
- ...
- ...
See also #10
/area documentation
/area control-plane
> adds information about IM configuration and usage

- internal/controller/gardener_cluster_controller.go
- Change the logic of reconciliation on unrecoverable error.
> Change the logic of reconciliation on unrecoverable error

- internal/controller/gardener_cluster_controller.go
Fix bug causing kubeconfig not being rotated.
> Fix kubeconfig rotation

- README.md
- fixes link to the license file
- ...
- ...
> fixes link to the license file

- internal/controller/gardener_cluster_controller.go
- should fix the regression in secrets rotation 
- ...
- ...
> fixes rotation regression

- .github/workflows/daily-markdown-link-check.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/pr-markdown-link-check.yaml
- .github/workflows/run-tests.yaml
- .github/workflows/run-vuln-check.yaml
> [IM] Rename the GitHub Actions

- docs/contributor/testing-strategy.md
Doc adjustment according to the [guideline](https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/03-formatting.md#ordered-and-unordered-lists) 
> use lists to create visual clarity within your content. List items in a category or in a sequence. Use an ordered list for sequential, instructional steps. Unordered lists are appropriate for items that have no sequential order, such as a list of valid file types. Follow these guidelines:
> Unordered lists are appropriate for items that have no sequential order

- go.mod
-  bumps golang to 1.22.1
- ...
- ...
Will unblock #165
> bumps golang to 1.22.1

- Dockerfile
- go.mod
- bumps golang to 1.22.2
- ...
- ...
> bumps golang to 1.22.2

- cmd/main.go
- config/default/manager_gardener_secret_patch.yaml
- docs/README.md
- internal/controller/runtime_controller.go
- Feature flag that enables provisioning added
- Gardener Clients passed to the Runtime controller
> Added feature flag that controls provisioning

- hack/runtime-migrator/README.md
- fixes misformated code section
- ...
- ...
#183
> fixes misformated code section

- hack/runtime-migrator/main.go
- oidc config is also migrated to additionalOidcs field
- removes not needed shoot labels
- ...
#242
> oidc config is also migrated to additionalOidcs field + removes not needed shoot labels

- go.mod
- internal/controller/runtime_controller.go
- internal/gardener/shoot/converter.go
- internal/gardener/shoot/converter_test.go
- internal/gardener/shoot/extender/exposure_classname_extender.go
- internal/gardener/shoot/extender/exposure_classname_extender_test.go
- internal/gardener/shoot/extender/kubernetes_version_test.go
- internal/gardener/shoot/extender/network_filter.go
- internal/gardener/shoot/extender/network_filter_test.go
- adds networking filter extender
- adds exposureClassName extender
- enables cloud profile extender
#231
> networking filter and cloud profile extenders

- config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
- internal/controller/runtime/fsm/runtime_fsm_common.go
- internal/controller/runtime/fsm/runtime_fsm_initialise.go
Change delete Runtime CR to wait on Shoot CR delete.
- https://github.com/kyma-project/infrastructure-manager/issues/209
> Change delete Runtime CR to wait on Shoot CR delete

- api/v1/runtime_types.go
- Aims to fix the issue described in [here](https://github.com/kyma-project/infrastructure-manager/pull/293#issuecomment-2236399401).
- ...
- ...
#282
> switches to shoot-name label instead of shootName

- .github/workflows/build_shoot_compare.yml
- Fix invalid Dockerfile path in shoot-comparator workflow
- https://github.com/kyma-project/infrastructure-manager/issues/185
> Fix invalid Dockerfile path in shoot-comparator workflow

- cmd/main.go
- docs/README.md
- internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
- internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
- internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
- internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
- Renames persist-shoot to dump-shoot-spec
- please be aware of related PR in internal MPC repository #1776 that should be merged as well
- part of https://github.com/kyma-project/infrastructure-manager/issues/185#issuecomment-2216825908
> Renames persist-shoot to dump-shoot-spec

- internal/gardener/shoot/extender/provider.go
- internal/gardener/shoot/extender/provider_test.go
- implements #284 
- ...
- ...
> disables sshAccess by default

- internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
- internal/controller/runtime/fsm/utilz_for_test.go
Adapt tests to auditlogs changes.
- tests adapted to auditlogs changes
- https://github.com/kyma-project/infrastructure-manager/issues/286
> Adapt tests to auditlogs changes

- internal/auditlogging/auditlogging.go
- internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
- internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go
- internal/controller/runtime/fsm/runtime_fsm_configure_auditlog_test.go
- internal/controller/runtime/fsm/runtime_fsm_waiting_for_shoot_reconcile.go
- internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
- internal/controller/runtime/runtime_controller_test.go
- internal/controller/runtime/suite_test.go
- internal/controller/runtime/testdata/auditConfig.json
- waiting ensures that the audit log configuration applied was correct
#286
> Waiting for Gardener shoot to be in Ready state after configuring Audit Log

- .github/workflows/build_kim.yaml
- migrate build pipeline from Prow
> Migrate build pipeline

- Dockerfile
> Bump docker image

- .github/workflows/run-tests.yaml
- change the GH Action filters
> Fix GH Action `tests` in KIM

- internal/controller/runtime/fsm/runtime_fsm_configure_auditlog.go
- fixes logger panic for even number of parameters
- fixes logger panic for bool value instead of string
#286
> fixes logger panics

- internal/gardener/shoot/hyperscaler/gcp/config.go
- internal/gardener/shoot/hyperscaler/gcp/config_test.go
> Add worker field to GCP

- hack/shoot-comparator/cmd/comparator/directories.go
- hack/shoot-comparator/internal/directories/comparator.go
- hack/shoot-comparator/scripts/README.md
- hack/shoot-comparator/scripts/manifests/job.yaml
- hack/shoot-comparator/scripts/manifests/mount-kim-volume-with-write-access.yaml
- hack/shoot-comparator/scripts/manifests/mount-prov-volume-with-write-access.yaml
- internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
- internal/controller/runtime/fsm/runtime_fsm_persist_shoot_test.go
- internal/gardener/shoot/converter.go
- Fixed the way comparator filters shoot files
- KIM adds `creationTimestamp` to allow comparator to filter out files older than specific date
https://github.com/kyma-project/control-plane/issues/3478
> Fix compare job

- internal/controller/runtime/fsm/runtime_fsm_take_snapshot.go
- Fixed problem with storing shoot spec in dry run mode
> Skip getting shoot if runtime is controlled  by the provisioner

- hack/shoot-comparator/cmd/comparator/directories.go
- hack/shoot-comparator/cmd/comparator/files.go
- hack/shoot-comparator/cmd/main.go
- hack/shoot-comparator/go.mod
- hack/shoot-comparator/internal/directories/comparator.go
- hack/shoot-comparator/internal/files/comparator.go
- change module path from `/tools` to `/hack`
> Change invalid `shoot-comparator` module name

- pkg/gardener/shoot/extender/dns.go
- pkg/gardener/shoot/extender/dns_test.go
- DNS extender sets dns extension fields to avoid unnecessary shoot reconciliations, and allow migrator to proceed with applying Runtime CR   
#400
> Implemented changes in DNS extender

- hack/shoot-comparator/pkg/shoot/matcher.go
- hack/shoot-comparator/pkg/shoot/matcher_test.go
- Added `CloudProfileName` to matcher
#400
> Fixed regression in Comparator tests

- pkg/gardener/shoot/extender/network_filter.go
- pkg/gardener/shoot/extender/network_filter_test.go
- Fix for enabling network filter extension
#400
> Fixed issue with enabling network filter extension

- .github/workflows/build_kim.yaml
> Add latest tag on main

- .github/workflows/build_kim.yaml
> fix failing trivy job

- .github/workflows/build_kim.yaml
> fix yaml error

- .github/workflows/build_kim.yaml
> Fix latest label

- .github/workflows/build_kim.yaml
> Fix latest tag

- .github/workflows/build_kim.yaml
> Fix latest

- .github/workflows/build_kim.yaml
> Use single quotes

- pkg/gardener/shoot/extender/dns.go
- pkg/gardener/shoot/extender/dns_test.go
- adds a resource required by Gardener's admission webhook
- ...
- ...
https://github.com/kyma-project/infrastructure-manager/pull/460
> creates NamedResourceReference for DNS secret

- internal/controller/runtime/fsm/runtime_fsm_create_shoot.go
- internal/controller/runtime/fsm/runtime_fsm_create_shoot_dry_run.go
- internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
- internal/controller/runtime/fsm/runtime_fsm_persist_shoot.go
- internal/controller/runtime/suite_test.go
- pkg/gardener/shoot/converter.go
- pkg/gardener/shoot/converter_test.go
- pkg/gardener/shoot/extender/auditlogs/extender.go
- pkg/gardener/shoot/extender/auditlogs/extender_test.go
- pkg/gardener/shoot/extender/auditlogs/set_extension.go
- pkg/gardener/shoot/extender/auditlogs/set_extension_test.go
- pkg/gardener/shoot/extender/auditlogs/set_policy_configmap.go
- pkg/gardener/shoot/extender/auditlogs/set_policy_configmap_test.go
- pkg/gardener/shoot/extender/auditlogs/set_secret.go
- pkg/gardener/shoot/extender/auditlogs/set_secret_test.go
- new audit log extenders
- refactor converters
See also: https://github.com/kyma-project/infrastructure-manager/issues/470
> New audit log extenders

- .github/workflows/build_kim.yaml
- removes trivy as it is failing because of external db connection issue
- ...
- ...
> removes trivy

- internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
- Fixed panic on error logging in delete shoot
> Fixed logging issue

- internal/controller/runtime/fsm/runtime_fsm_delete_shoot.go
Restore old workaround for patching shoot during deleting it
> Fix for deleting shoot - adding additional fields

- hack/runtime-migrator/cmd/main.go
- hack/runtime-migrator/cmd/migration.go
- migrator's timeout issue fixed
> fix issue with migrator's timeout

- hack/runtime-migrator/internal/runtime/verifier.go
- hack/shoot-comparator/internal/files/comparator.go
- hack/shoot-comparator/pkg/shoot/matcher.go
- hack/shoot-comparator/pkg/shoot/matcher_test.go
- pkg/gardener/shoot/converter.go
- pkg/gardener/shoot/converter_test.go
- Fix shoot converter not to override dns settings
- fix dns matcher
> Fix shoot converter not to override dns settings

- api/v1/runtime_types.go
- internal/controller/runtime/fsm/runtime_fsm_waiting_shoot_creation.go
- set error state if seed not found
#511
> Set error state, if seed doesn't exist in required region

- internal/controller/runtime/runtime_controller.go
> Fix logging shoot name

- internal/controller/runtime/fsm/runtime_fsm_apply_clusterrolebindings.go
- internal/controller/runtime/fsm/runtime_fsm_apply_crb_test.go
- Fix bug causing unwanted CRB deletion
- Add missing test cases
> Fix bug causing crb removal

- internal/controller/runtime/fsm/runtime_fsm_configure_oidc.go
- requeue when oidc cr creation fails 
- ...
- ...
> requeue when oidc cr creation fails

- pkg/gardener/shoot/extender/annotations_test.go
- fail a test in order to test tide replacement
- ...
- ...
> fail a test in order to test tide replacement

- pkg/gardener/shoot/extender/annotations_test.go
Revert #666 that shouldn't be merged
> Revert "fail a test in order to test tide replacement"

- internal/controller/runtime/fsm/runtime_fsm_patch_shoot.go
- internal/controller/runtime/fsm/runtime_fsm_patch_shoot_test.go
- internal/controller/runtime/suite_test.go
- Add waiting for shoot synchronisation
#674
> First approach to fixing worker synchronisation problem

- pkg/gardener/gardener_error_handler.go
- pkg/gardener/gardener_error_handler_test.go
Small change to treat Gardener error response with code ERR_CONFIGURATION_PROBLEM as retryable
> Handling Gardener error ERR_CONFIGURATION_PROBLEM as retryable 

- pkg/gardener/shoot/converter.go
- pkg/gardener/shoot/extender/annotations.go
- pkg/gardener/shoot/extender/annotations_test.go
- pkg/gardener/shoot/extender/restrictions/restrictions.go
- pkg/gardener/shoot/extender/restrictions/restrictions_test.go
- adjust setting of the `eu-access` restrictions on Shoots
#663
> Migrate to the new way of setting `eu-access` restrictions on Shoots

- renovate.json
Instead of updating Renovate PRs manually, it should now do that automatically.
> rebase renovate PRs automatically

- renovate.json
Changes:
- disable pr hourly limit so all PRs will be created early Monday
> disable pr hourly limit

- .github/workflows/run-tests.yaml
[coveralls.io](https://coveralls.io) is the coverage badge used in [kubernetes-sigs/kubebuilder](https://github.com/kubernetes-sigs/kubebuilder). It's authorised in `kyma-project`. It will give us online preview of the coverage and the badge
> Add coveralls integration

- .github/workflows/run-tests.yaml
- api/v1/runtime_types.go
- config/crd/bases/infrastructuremanager.kyma-project.io_runtimes.yaml
- internal/controller/runtime/fsm/testing/shoot.go
- internal/controller/runtime/suite_test.go
> Filter coverage
